[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "cloudscraper>=1.2.71",
    "fake-useragent>=2.2.0",
    "lxml>=6.0.0",
    "requests>=2.32.4",
]
